version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: 
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      EVENT_MANAGER_DATABASE_HOST: db
      EVENT_MANAGER_DATABASE_NAME: myapp
      EVENT_MANAGER_DATABASE_USERNAME: myapp
      EVENT_MANAGER_DATABASE_PASSWORD: password
      RAILS_MASTER_KEY: 
      RAILS_ENV: development

volumes:
  db_data: