EVENT_MANAGER_DATABASE_USERNAME: root
EVENT_MANAGER_DATABASE_PASSWORD: 
EVENT_MANAGER_DATABASE_HOST: localhost
EVENT_MANAGER_DATABASE_NAME: event_manager_database
MAPS_API_KEY: AIzaSyDA10MPtVw9HsarZk1scKS-JYZh_yKhZAo